import { StoreFooter, StoreHeader } from '@/components/storefront';
import { AccountShell } from '@/components/account-shell';
import { Badge, Button, ButtonLink, Card, EmptyState, Field, PageHeader } from '@/components/ui';
import { requireUser } from '@/lib/auth/rbac';
import { supabaseAdmin } from '@/lib/supabase/server';
import { deleteAddress, saveAddress, setDefaultAddress } from '@/lib/customer/actions';

export default async function AddressesPage() {
  const user = await requireUser();
  const { data: addresses } = await supabaseAdmin.from('addresses').select('*').eq('user_id', user.id).order('created_at');
  return <><StoreHeader /><AccountShell user={user}><div className="space-y-6"><PageHeader eyebrow="Account" title="Addresses" description="Manage shipping destinations for faster checkout." /><Card><h2 className="text-xl font-semibold theme-heading">Add address</h2><p className="mt-1 text-sm theme-text-muted">Phone: 8-20 digits/spaces/+/- · postal code: 4-10 digits.</p><form action={saveAddress} className="mt-4 grid gap-3 md:grid-cols-2">{['recipient_name','phone','province','city','district','postal_code'].map((n) => <Field key={n} label={n.replace('_', ' ')}><input name={n} required /></Field>)}<Field label="full address"><textarea name="full_address" required /></Field><Field label="notes"><input name="notes" /></Field><label className="flex items-center gap-2 text-sm theme-text"><input type="checkbox" name="is_default" /> Default address</label><Button>Save address</Button></form></Card>{addresses?.length ? <div className="grid gap-4 md:grid-cols-2">{addresses.map((a) => <Card key={a.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold theme-heading">{a.recipient_name}</p><p className="text-sm theme-text-muted">{a.phone}</p></div>{a.is_default ? <Badge>Default</Badge> : null}</div><p className="mt-3 text-sm theme-text-muted">{a.full_address}, {a.district}, {a.city}, {a.province} {a.postal_code}</p>{a.notes ? <p className="mt-2 text-sm theme-text-muted">Notes: {a.notes}</p> : null}<div className="mt-4 flex flex-wrap gap-2"><ButtonLink href={`/account/addresses/${a.id}/edit`} variant="secondary" size="sm">Edit</ButtonLink><form action={setDefaultAddress}><input type="hidden" name="id" value={a.id} /><Button variant="ghost" size="sm">Set default</Button></form><form action={deleteAddress}><input type="hidden" name="id" value={a.id} /><Button variant="danger" size="sm" disabled={addresses.length === 1}>Delete</Button></form></div></Card>)}</div> : <EmptyState icon="⌂" title="No address yet" description="Add your first shipping address to continue checkout faster." />}</div></AccountShell><StoreFooter /></>;
}
