/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { StoreFooter, StoreHeader } from '@/components/storefront';
import { AccountShell } from '@/components/account-shell';
import { requireUser } from '@/lib/auth/rbac';
import { supabaseAdmin } from '@/lib/supabase/server';
import { clearCart, removeCartItem, updateCartQuantity } from '@/lib/customer/actions';
import { imageUrl } from '@/lib/public/catalog';

export default async function CartPage({searchParams}:{searchParams:Promise<{error?:string}>}){
  const user=await requireUser();
  const params=await searchParams;
  const {data:cart}=await supabaseAdmin.from('carts').select('id').eq('user_id',user.id).maybeSingle();
  const {data:items}=cart?await supabaseAdmin.from('cart_items').select('id,quantity,products(id,name,slug,price,discount_price,stock,product_images(file_path,is_primary,alt_text,sort_order)),product_variants(id,name,sku,price,discount_price,stock)').eq('cart_id',cart.id):{data:[]};
  const total=(items??[]).reduce((sum,item)=>{const p=Array.isArray(item.products)?item.products[0]:item.products; const v=Array.isArray(item.product_variants)?item.product_variants[0]:item.product_variants; return sum + Number(v?.discount_price??v?.price??p?.discount_price??p?.price??0)*item.quantity},0);
  return <><StoreHeader/><AccountShell user={user}><h2 className="text-2xl font-semibold theme-heading">Cart</h2>{params.error==='stock'?<p className="mt-3 rounded-2xl bg-[var(--surface-muted)] p-3 text-sm theme-brand">Quantity exceeds available stock.</p>:null}<div className="mt-6 grid gap-4">{items?.map((item)=>{const p=Array.isArray(item.products)?item.products[0]:item.products; const v=Array.isArray(item.product_variants)?item.product_variants[0]:item.product_variants; const img=[...(p?.product_images??[])].sort((a,b)=>Number(b.is_primary)-Number(a.is_primary))[0]; const price=Number(v?.discount_price??v?.price??p?.discount_price??p?.price??0); return <div key={item.id} className="grid gap-4 rounded-3xl border theme-border p-4 md:grid-cols-[96px_1fr_auto]"><div className="aspect-square rounded-2xl bg-[var(--surface-muted)]">{img?<img src={imageUrl('products',img.file_path)??''} alt={p?.name??''} className="h-full w-full rounded-2xl object-cover"/>:null}</div><div><p className="font-medium theme-text">{p?.name}</p>{v?<p className="text-sm theme-text-muted">{v.name} · {v.sku}</p>:null}<p className="text-sm theme-text-muted">Rp {price.toLocaleString('id-ID')}</p><p className="text-sm theme-text-muted">Subtotal Rp {(price*item.quantity).toLocaleString('id-ID')}</p></div><div className="flex items-center gap-2"><form action={updateCartQuantity}><input type="hidden" name="id" value={item.id}/><input name="quantity" type="number" min="1" defaultValue={item.quantity} className="w-20 rounded-full bg-[var(--surface-muted)] px-3 py-2"/><button className="ml-2 theme-brand">Update</button></form><form action={removeCartItem}><input type="hidden" name="id" value={item.id}/><button className="theme-text-muted">Remove</button></form></div></div>})}</div><div className="mt-8 rounded-3xl bg-[var(--surface-muted)] p-6 theme-text"><p>Subtotal: Rp {total.toLocaleString('id-ID')}</p><p>Shipping: Rp 0</p><p className="mt-2 font-semibold">Total: Rp {total.toLocaleString('id-ID')}</p><div className="mt-4 flex flex-wrap items-center gap-3"><form action={clearCart}><button className="theme-brand">Clear cart</button></form>{items?.length?<Link href="/checkout" className="rounded-full px-6 py-3 theme-button">Checkout</Link>:<button disabled className="rounded-full px-6 py-3 theme-button-soft">Cart is empty</button>}</div></div></AccountShell><StoreFooter/></>;
}
